### ISSUE TITLE
Create prototype workflow for building PDX application ontology

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/ebispot.github.io#26]
Zoe has the details.

**Comment by zoependlington** [comment]
"Task, build an NCIt slim for PDX. 

Requirements. 

Given a list of NCIT terms 

Extract a module from latest NCIT OBO edition
Apply custom labels and definitions from a text file
From the initial list of terms create a slim of the NCIT module

Tasks 

- [ ] Create a new ontology starter kit project using https://github.com/INCATools/ontology-starter-kit 
- [ ] Build a workflow using ROBOT http://robot.obolibrary.org 
- [ ] May need owltools for the slimming or additional code
- [ ] Add the workflow to the makefile
- [ ] Set up additional test using the sparql tests
- [ ] Document the process
- [ ] Setup travis for continuous testing "

Current github repo can be found here: https://github.com/zoependlington/pdx-ontology

**Comment by zoependlington** [comment]
Make file now takes terms from pdx-cancer.tsv, creates a slim, merges with ncit.owl and extracts all annotations into pdxo.owl.

The demo PDX application ontology can be found at https://github.com/zoependlington/pdx-ontology/blob/master/pdxo.owl .

**Comment by zoependlington** [comment]
A few edits since the last update:
- Updated the makefile to prevent duplicate rdfs:labels (implemented through python script).
- Allowed preferred labels (skos:prefLabel) to be defined in the template (currently, a preferred label must be supplied in the template but the plan is to implement a SPARQL query to automatically generate a prefLabel if it is missing from the rdfs:label.)
- Tested synonyms and definition additions to template and fixed bug that showed skos:prefLabel, hasExactSynonym and IAO_0000115 to appear as classes.
